# Generated by Django 6.0.7 on 2026-07-12 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_servicerecord_end_time_servicerecord_start_time_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_daily_reporter',
            field=models.BooleanField(default=False, help_text='ONの場合、この従業員がこの利用者の日報提出対象になる', verbose_name='日報担当'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], verbose_name='曜日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('is_daily_reporter', models.BooleanField(default=False, verbose_name='日報担当')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to=settings.AUTH_USER_MODEL, verbose_name='従業員')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_patterns', to='dashboard.user', verbose_name='利用者')),
            ],
            options={
                'verbose_name': 'シフトパターン',
                'verbose_name_plural': 'シフトパターン',
                'ordering': ['weekday', 'employee_id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'user', 'weekday'), name='unique_pattern_employee_user_weekday')],
            },
        ),
    ]
